### ISSUE TITLE
OS再インストール用のサブコマンドを追加してほしい

### ISSUE THREAD

**Issue by wate** [sacloud/vagrant-sakura#25]
以下の用途で利用する場合、破棄して作り直すと効率が悪いため、
OS再インストールのAPIを呼び出すサブコマンドを追加してほしい

### 利用シーン

作成途中のスタートアップスクリプトや、他の構成管理ツールの動作検証をする場合

**Comment by yamamoto-febc** [comment]
> 破棄して作り直すと効率が悪い

破棄した場合と再インストールした場合でどの辺りの効率が問題でしょうか？

破棄して作り直す場合もOS再インストールAPI呼び出しもユーザーの待ち時間としてはさほど変わらないと思っています。

サーバの破棄/作成などのAPI呼び出し回数は作り直しを行う時の方が多いですが、これらは即時応答のあるAPIで待ち時間は少ないです。
時間がかかるのはディスクのコピーやサーバの起動/シャットダウン待ちなどで、これは作り直し/再インストールとも変わらないです。

このため、再インストール用のサブコマンドを作る場合、内部的に`destroy`と`up`と同じ処理を行い、OS再インストールAPIを呼ぶ部分は作らなくていいと考えています。

もし他の視点でOS再インストールAPIを利用した方が良い面があればおしらせください！

**Comment by wate** [comment]
@yamamoto-febc 
> もし他の視点でOS再インストールAPIを利用した方が良い面があればおしらせください！

再インストール時の時間というよりもdestroyしてupし直すと
サーバーのIPアドレスが変わってしまうので、
そういった部分で無駄な作業が発生してしまうのでそれを避けたいかなと。

例としては以下のようなケースですかね

開発中の環境をクライアントに通知している場合、
IPアドレスが変わるとそれを通知しなおさないといけない
また、DNSを利用していた場合でも、DNSの設定変更を行わなければならない
※OSの再インストールであればディスクの修正だけなのでサーバー自体のIPアドレスが変わらないので

**Comment by yamamoto-febc** [comment]
ありがとうございます！IPアドレスを変えたくないという場合に有効ですね:smile:
ではv0.1.0での実装予定しておきます:+1:

**Comment by wate** [comment]
あざっす！👍
